### ISSUE TITLE
[question] + [suggestions]

### ISSUE THREAD

**Issue by thednp** [PitPik/colorPicker#14]
* do you consider developing a palettes generator? (10 shims, complimentary, see <a href="http://paletton.com/">here</a> what I mean/like)
* Don't waste time with jQuery!!
* currently has the option to exclude rgba?

Thanks!!

**Comment by PitPik** [comment]
Hi @thednp 

thanks for your feedback and your stars ;o)
 - palettes generator: with colors.js and some module extensions for color-geometry calculations, this would be an easy one to do. I thought about it already but there is so many nice ones out there already like colour lover, Kuler, Color Explorer, Pictaculous, etc... and so little time at night ;o)... I can't really imagine what I could add to those nice examples.
If I ever find something that I could do better... I will go for it and make it.
 - jQuery: Shouldn't I waste time with jQuery as my examples are so bad? ;o)
I see a lot of people not being interested in javascript only stuff as it's considered old-fashioned... so, sometimes I smuggle some jQuery into my projects. My tinyColorPicker was done though in one afternoon, and it is fun to mangle jQuery once in a while.
 - exclude rgba: well, I hope I do understand this right: with the option `noAlpha` you can get rid of the alpha slider and alpha input box. So all colors will be solid...

Thanks again and keep on the good spirit.
Cheers,
Peter

**Comment by thednp** [comment]
Man this is by far an amazing color picker, I couldn't believe it's even build with rAF animation support. Are you kidding me?

For supporting jQuery you only need a fn definition at the bottom of your code, why rewrite the entire code for the sake of jQuery... man... the trends are going back to plain Javascript since HTML5 JS engine kicked out stable and nowadays we have polyfills for legacy browsers....

Thanks for your reply and your wonderful work, now gonna head to replace bootstrap color with this one, I really needed a high precision color picker and I think this one really delivers :)
