### ISSUE TITLE
Does it support no default value?

### ISSUE THREAD

**Issue by arlonlove** [PitPik/colorPicker#17]
I need to use it whith out default value.

**Comment by PitPik** [comment]
Hi @arlonlove 
its hard to answer with this little information... do you mean the color picker itself, the jQuery implementation or the javascript implementation?
The color picker always needs to show something, so for the UI: no.
The implementations are more like demos to show how to use colorPicker, so they are meant to be tweaked. Right now, if you leave the values of the input fields in both implementations empty you'll get a javascript error (other than in https://github.com/PitPik/tinyColorPicker, where the value can be empty),
but that is easy to fix though.

**Comment by PitPik** [comment]
@arlonlove 
I fixed the issue with empty values. Now you can have just an input field without any value. It defaults to #FFFFFF when you activate it. Both, javaScript and jQuery implementation support this now.
