### ISSUE TITLE
Is it supported by mpbile device?

### ISSUE THREAD

**Issue by anna647** [PitPik/colorPicker#21]
hi.
could you tell me how can I let it can work well in the mobile device? I have tried but failed. Maybe I initialized it in a way way. Could you tell me the right way? Thanks.

**Comment by PitPik** [comment]
Hi @anna647 
unfortunately this thing is not quite well usable for mobile. There is also too much going on to make it worth running on mobile. For a good mobile version you should use my other color-picker: https://github.com/PitPik/tinyColorPicker
Good luck
