### ISSUE TITLE
[Question] Hook into color update?

### ISSUE THREAD

**Issue by thednp** [PitPik/colorPicker#22]
I was searching your doc and cound't find any clue, basically what I'm after is similar to 

```
init: function(elem,colors){
//do some stuff
}
```

Yes, there is this
```
actionCallback: function(e,action) {}
```
But I don't know what are those function attributes for.

So yes, I would need to do some stuff on update.

Thanks so much.

**Comment by thednp** [comment]
I managed to make it work via `renderCallback`.

**Comment by thednp** [comment]
Hey there. 

We need a way to have access to element in all callback functions. Can you please point out or make some improvements on this? 

Thank you

**Comment by thednp** [comment]
I found that to get the element in the callback functions you can simply do

```
var myInput = this.input;
```

But I think this should be documented.

**Comment by PitPik** [comment]
Hi @thednp 
sorry for the late answer,... I was not home for quite a while.
Thanks for your point. I will update the documentations as soon as I find time.
Cheers
