### ISSUE TITLE
How to use setColor? Can't find examples, can't figure it out

### ISSUE THREAD

**Issue by daattali** [PitPik/colorPicker#24]
Hey, I like your plugin, and I want to use it in a package I'm writing in R (programming language). One thing I can't figure out is how to set the color of an existing input?  I see that you can somehow "extend" with proto, but I can't figure out - can you show an example?

**Comment by PitPik** [comment]
Hi @daattali 
thanks for your comment.
I don't understand exactly what you need though... there is no "extending" with proto..
I also don't know what part you're using... setColor is a method of colors.js and colorPicker.js and can also be used by with the implementation examples.
setColor can set the values in the color model and if used with colorPicker.js will update the color picker as well,... how to update an input field depends on how you use color picker.
Too less information to make wild guesses ;o)
