### ISSUE TITLE
Typing mistake (appendTo property)

### ISSUE THREAD

**Issue by ZeStrid3r** [PitPik/colorPicker#27]
Hi, the "appendTo" property cannot works because of a typing error :

**jsColor.js - line 118**
```
(options.appenTo || document.body).appendChild(colorPickerUI);
```

Just replace *"appenTo"* by *"appendTo"* to fix it. :)

**Comment by PitPik** [comment]
Hey @ZeStrid3r thanks!!
I updated.
Thanks for your participation
