### ISSUE TITLE
Erroron bower

### ISSUE THREAD

**Issue by johnkottis** [PitPik/colorPicker#28]
I am getting the following error when I do a bower install

Error Message: enotfound package colorPicker not found

**Comment by pasqLisena** [comment]
This is because this color picker is not on bower.

Please add it!!!  :pray: :smile:

**Comment by PitPik** [comment]
tinyColorPicker (https://github.com/PitPik/tinyColorPicker) is on bower, maybe that helps (```bower install tinyColorPicker```).
Until I haven't updated the implementations, I won't put colorPicker on bower. Sorry, but this could take a while ;o)
