### ISSUE TITLE
Convert Color

### ISSUE THREAD

**Issue by Horray** [PitPik/colorPicker#33]
How can I make a simple conversion? Say from HSV to HSL?

I tried the following:

    var myColor = new Colors();
    var hslColor = myColor.convertColor({
        h: 100,
        s: 100,
        v: 100
    },'hsv2hsl')
    console.log(hslColor);

And I get the folloinwg output:

    Object {h: 100, s: -1.0204081632653061, l: -4900}

How can I get regular output?

**Comment by PitPik** [comment]
Hi @Horray ,
I saw your post yesterday already... so I guess you found out yourself.
The only thing you have to be aware: ```hsl```is not the same as ```HSL```(the same for all others). So your code would be then:
```javascript
var myColor = new Colors();
var hslColor = myColor.convertColor({
    h: 100,
    s: 100,
    v: 100
},'HSV2HSL')
console.log(hslColor);
```
You'll then get:
```javascript
Object {h: 100, s: 100, l: 50}
```
So you have a huge span of conversion possibilities:
```hsv2HSV, hsv2hsl, hsv2HSL, HSV2hsl, HSV2HSL, ...```
The capital letters are representative for values you're talking about (0-360, 0-100, 0-100) (rounded) and small letters mean normalized values, so 0-1 (float).
It might be a little confusing that you have to write the object ```{h: 100, ..}``` in small letters, but with the following string ```'HSV2HSL'``` you then actually describe from where to where it should convert.
```HEX``` and ```XYZ``` don't follow this rule and the difference between ```LAB``` and ```Lab``` is that ```LAB``` is rounded to integers.

I hope this helped you a bit.
Good luck and Cheers

**Comment by Horray** [comment]
Thank you! Yes it did indeed help a lot!

Wooooow!! 182 different possibilities!!! Amazing!

**Comment by Horray** [comment]
How can I convert a string to an RGB color? I know it's possible doing it, because there's a function at line [344 in color.js](https://github.com/PitPik/colorPicker/blob/master/colors.js#L344). I tried the following:

```
myColor.convertColor('rgb(100, 50, 100)', 'txt2RGB');
myColor.ColorConverter.txt2color(rgb(100, 50, 100)');
```
And they all didn't work. They gave me an error.

Thanks!
