### ISSUE TITLE
Picking color from L*a*b parameters

### ISSUE THREAD

**Issue by kimtore** [PitPik/colorPicker#61]
First of all, this is hands down the best color picker I could find. It is responsive and feature-rich, thanks for your good work.

I am making a frontend to a LED lamp, and came looking for a way to select a color using L\*a\*b parameters. This project seems like a very good fit for my use case, especially because of the intuitive and fast interface. My problem is that I can't find a way of actually using the L\*a\*b space for picking out colors, it seems that only RGB, HSL and HSV are supported.

Can you offer some help in this regard?

**Comment by PitPik** [comment]
Hi @ambientsound Kim,
thanks for the flowers ;o)
Unfortunately I only support the input / output of Lab but not the visual support as it is very complex to do with simple web technology (back then, as I also wanted to support IE5.5). I could probably do it with <canvas> or so but this would totally explode the project as I wanted it to keep small and simple. Rendering RGB is already a challenge for most color pickers.
Good luck though with your project.

**Comment by kimtore** [comment]
Hi, and thanks for your reply.

Your priorities make sense. It seemed to me like a small feature addition, I was not aware that it is so complex. Thanks anyway, I will re-think my approach.

Have a good day :)
