### ISSUE TITLE
simple jsFiddle with realistic example

### ISSUE THREAD

**Issue by tammo0** [PitPik/colorPicker#7]
Hi @PitPik,

first of all: Thanks for your work! Your colorPicker looks amazing.
Perhaps i dont get it and its the wrong Picker for my scenario, so please dont mind if i didnt understand your intention.

I looked at your examples and the demo page but i still dont get it.

This is what i try to get:
You have a button which opens the colorPicker on click.
It can have an initial color (eg by comming from a database or cookie).
When you change the color with the picker i want to execute a function (eg. an ajax call or a function which updates styles of some elements with the new color).
But i still dont get how to initialize it neighter how to listen to events.

Can you provide a simple jsFiddle?

Kind regards

**Comment by ghost** [comment]
@PitPik please send the instance in renderCallback and in actionCallback, you don't need to work with the internal api if you send the color picker instance (cp-app) in the first parameter of both functions. 

**Please note:**
Will not be allowed have different behaviour for a particular instance by default, but also the instances can have a reference to the target element (input, button?) with an id and you can detect who instance is and if is belong to what target if you associate the picker to the target element internally.
